# Generated by Django 3.0.7 on 2020-09-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200930_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='ArticlePics'),
            preserve_default=False,
        ),
    ]
