# Generated by Django 3.0.7 on 2020-09-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_post_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
    ]
