# Generated by Django 3.0.7 on 2020-09-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_post_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
