# Generated by Django 3.0.7 on 2020-09-30 10:24

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
    ]
