# Generated by Django 3.0.7 on 2020-10-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20201006_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avartar.jpg', upload_to='ProfilePics'),
        ),
    ]
